### ISSUE TITLE
Sutsis: Checking for definitions in other languages if the searched word yields no result for the currently selected language.

### ISSUE THREAD

**Issue by Ilmen-vodhr** [Ilmen-vodhr/ilmentufa#95]
That's nothing urgent, but someday it would be nice that if the searched word yields no result in the currently selected language, Sutsis outputs something like «No definition found for the ••• language. However this word has definitions for [Lojban], [ThisLanguage], [ThatLanguage].»

For example sometimes words have only Lojban definitions, so if somebody searches for them in the English inteface, it'll seem that these words don't exist at all.

If checking every other language dumps for a definition is a problem, maybe just checking the Lojban and English dumps would suffice.

**Comment by lagleki** [comment]
better to think of replacing the current bulky sutsis'es dump with a
database file and a pure javascript database engine like mongo.

2015-02-25 19:10 GMT+03:00 Ilmen <notifications@github.com>:

**Comment by lagleki** [comment]
>> If checking every other language dumps for a definition is a problem, maybe just checking the Lojban and English dumps would suffice.

This may be done by using two xml dumps to produce a larger sutsis'es dump including english and lojban definitions.

**Comment by lagleki** [comment]
Could also be considered for la naxle
